#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.5
#  in conjunction with Tcl version 8.6
#    Aug 16, 2022 01:59:50 AM +03  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_script = sys.argv[0]
_location = os.path.dirname(_script)

import alsattool_support

_bgcolor = '#d9d9d9'  # X11 color: 'gray85'
_fgcolor = '#000000'  # X11 color: 'black'
_compcolor = 'gray40' # X11 color: #666666
_ana1color = '#c3c3c3' # Closest X11 color: 'gray76'
_ana2color = 'beige' # X11 color: #f5f5dc
_tabfg1 = 'black' 
_tabfg2 = 'black' 
_tabbg1 = 'grey75' 
_tabbg2 = 'grey89' 
_bgmode = 'light' 

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("374x778+1106+25")
        top.minsize(374, 1)
        top.maxsize(1924, 1829)
        top.resizable(1,  1)
        top.title("Binance Al Sat TOOL")
        top.configure(background="#d9d9d9")

        self.top = top
        self.selectedButton = tk.StringVar()
        tk.StringVar.set(self.selectedButton,"LONG")

        self.che46 = tk.IntVar()



        self.LimitAl = tk.Button(self.top)
        self.LimitAl.place(relx=0.08, rely=0.812, height=34, width=97)
        self.LimitAl.configure(activebackground="beige")
        self.LimitAl.configure(activeforeground="black")
        self.LimitAl.configure(background="#d9d9d9")
        self.LimitAl.configure(compound='left')
        self.LimitAl.configure(disabledforeground="#a3a3a3")
        self.LimitAl.configure(foreground="#000000")
        self.LimitAl.configure(highlightbackground="#d9d9d9")
        self.LimitAl.configure(highlightcolor="black")
        self.LimitAl.configure(pady="0")
        self.LimitAl.configure(text='''Limitden AL''')
        self.LimitAl.bind('<Button-1>',alsattool_support.btn_limit_click)

        self.MarketAL = tk.Button(self.top)
        self.MarketAL.place(relx=0.428, rely=0.812, height=34, width=97)
        self.MarketAL.configure(activebackground="beige")
        self.MarketAL.configure(activeforeground="black")
        self.MarketAL.configure(background="#d9d9d9")
        self.MarketAL.configure(compound='left')
        self.MarketAL.configure(disabledforeground="#a3a3a3")
        self.MarketAL.configure(foreground="#000000")
        self.MarketAL.configure(highlightbackground="#d9d9d9")
        self.MarketAL.configure(highlightcolor="black")
        self.MarketAL.configure(pady="0")
        self.MarketAL.configure(text='''Market AL''')
        self.MarketAL.bind('<Button-1>',alsattool_support.btn_market_click)

        self.Frame1 = tk.Frame(self.top)
        self.Frame1.place(relx=0.027, rely=0.013, relheight=0.695
                , relwidth=0.949)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#d9d9d9")

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.056, rely=0.055, height=23, width=104)
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Coin İsmi :''')

        self.Coin = tk.Entry(self.Frame1)
        self.Coin.place(relx=0.056, rely=0.092, height=20, relwidth=0.377)
        self.Coin.configure(background="white")
        self.Coin.configure(disabledforeground="#a3a3a3")
        self.Coin.configure(font="TkFixedFont")
        self.Coin.configure(foreground="#000000")
        self.Coin.configure(insertbackground="black")
        self.Coin.bind('<Enter>',alsattool_support.coinismi)

        self.Fiyat = tk.Entry(self.Frame1)
        self.Fiyat.place(relx=0.056, rely=0.216, height=20, relwidth=0.377)
        self.Fiyat.configure(background="white")
        self.Fiyat.configure(disabledforeground="#a3a3a3")
        self.Fiyat.configure(font="TkFixedFont")
        self.Fiyat.configure(foreground="#000000")
        self.Fiyat.configure(insertbackground="black")
        self.Fiyat.bind('<Enter>',alsattool_support.fiyat)

        self.Label2 = tk.Label(self.Frame1)
        self.Label2.place(relx=0.056, rely=0.173, height=23, width=34)
        self.Label2.configure(anchor='w')
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(compound='left')
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''Fiyat :''')

        self.Miktar = tk.Entry(self.Frame1)
        self.Miktar.place(relx=0.056, rely=0.340, height=20, relwidth=0.377)
        self.Miktar.configure(background="white")
        # self.Miktar.configure(cursor="fleur")
        self.Miktar.configure(disabledforeground="#a3a3a3")
        self.Miktar.configure(font="TkFixedFont")
        self.Miktar.configure(foreground="#000000")
        self.Miktar.configure(insertbackground="black")
        self.Miktar.bind('<Enter>',alsattool_support.miktar)

        self.Label3 = tk.Label(self.Frame1)
        self.Label3.place(relx=0.056, rely=0.298, height=21, width=54)
        self.Label3.configure(anchor='w')
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(compound='left')
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(text='''Miktar :''')

        self.karsiz = tk.Button(self.Frame1)
        self.karsiz.place(relx=0.668, rely=0.924, height=24, width=117)
        self.karsiz.configure(activebackground="beige")
        self.karsiz.configure(activeforeground="black")
        self.karsiz.configure(background="#5a85e7")
        self.karsiz.configure(compound='left')
        self.karsiz.configure(disabledforeground="#a3a3a3")
        self.karsiz.configure(font="-family {Segoe UI} -size 10")
        self.karsiz.configure(foreground="#000000")
        self.karsiz.configure(highlightbackground="#d9d9d9")
        self.karsiz.configure(highlightcolor="black")
        self.karsiz.configure(pady="0")
        self.karsiz.configure(text='''Karsız Çıkış''')
        self.karsiz.bind('<Button-1>', alsattool_support.karsiz_cikis)

        self.kar10 = tk.Button(self.Frame1)
        self.kar10.place(relx=0.668, rely=0.869, height=24, width=117)
        self.kar10.configure(activebackground="beige")
        self.kar10.configure(activeforeground="black")
        self.kar10.configure(background="#59b3e8")
        self.kar10.configure(compound='left')
        self.kar10.configure(disabledforeground="#a3a3a3")
        self.kar10.configure(foreground="#000000")
        self.kar10.configure(highlightbackground="#d9d9d9")
        self.kar10.configure(highlightcolor="black")
        self.kar10.configure(pady="0")
        self.kar10.configure(text='''%10 Karlı''')
        self.kar10.bind('<Button-1>', alsattool_support.kar_10)

        self.kar20 = tk.Button(self.Frame1)
        self.kar20.place(relx=0.668, rely=0.813, height=24, width=117)
        self.kar20.configure(activebackground="beige")
        self.kar20.configure(activeforeground="black")
        self.kar20.configure(background="#57eac1")
        self.kar20.configure(compound='left')
        self.kar20.configure(disabledforeground="#a3a3a3")
        self.kar20.configure(foreground="#000000")
        self.kar20.configure(highlightbackground="#d9d9d9")
        self.kar20.configure(highlightcolor="black")
        self.kar20.configure(pady="0")
        self.kar20.configure(text='''%20 Karlı''')
        self.kar20.bind('<Button-1>', alsattool_support.kar_20)

        self.kar30 = tk.Button(self.Frame1)
        self.kar30.place(relx=0.668, rely=0.758, height=24, width=117)
        self.kar30.configure(activebackground="beige")
        self.kar30.configure(activeforeground="black")
        self.kar30.configure(background="#56eb78")
        self.kar30.configure(compound='left')
        self.kar30.configure(disabledforeground="#a3a3a3")
        self.kar30.configure(foreground="#000000")
        self.kar30.configure(highlightbackground="#d9d9d9")
        self.kar30.configure(highlightcolor="black")
        self.kar30.configure(pady="0")
        self.kar30.configure(text='''%30 Karlı''')
        self.kar30.bind('<Button-1>', alsattool_support.kar_30)

        self.kar40 = tk.Button(self.Frame1)
        self.kar40.place(relx=0.668, rely=0.702, height=24, width=117)
        self.kar40.configure(activebackground="beige")
        self.kar40.configure(activeforeground="black")
        self.kar40.configure(background="#a5ff42")
        self.kar40.configure(compound='left')
        self.kar40.configure(disabledforeground="#a3a3a3")
        self.kar40.configure(foreground="#000000")
        self.kar40.configure(highlightbackground="#d9d9d9")
        self.kar40.configure(highlightcolor="black")
        self.kar40.configure(pady="0")
        self.kar40.configure(text='''%40 Karılı''')
        self.kar40.bind('<Button-1>', alsattool_support.kar_40)

        self.Long = tk.Radiobutton(self.top)
        self.Long.place(relx=0.053, rely=0.742, relheight=0.036, relwidth=0.182)
        self.Long.configure(activebackground="#77f34e")
        self.Long.configure(activeforeground="#77f34e")
        self.Long.configure(anchor='w')
        self.Long.configure(background="#77f34e")
        self.Long.configure(compound='left')
        self.Long.configure(disabledforeground="#a3a3a3")
        self.Long.configure(foreground="#000000")
        self.Long.configure(highlightbackground="#d9d9d9")
        self.Long.configure(highlightcolor="black")
        self.Long.configure(justify='left')
        self.Long.configure(selectcolor="#d9d9d9")
        self.Long.configure(text='''LONG''')
        self.Long.configure(variable=self.selectedButton,value="LONG")

        self.Short = tk.Radiobutton(self.top)
        self.Short.place(relx=0.294, rely=0.742, relheight=0.036, relwidth=0.209)

        self.Short.configure(activebackground="beige")
        self.Short.configure(activeforeground="black")
        self.Short.configure(anchor='w')
        self.Short.configure(background="#f5010a")
        self.Short.configure(compound='left')
        self.Short.configure(disabledforeground="#a3a3a3")
        self.Short.configure(foreground="#000000")
        self.Short.configure(highlightbackground="#d9d9d9")
        self.Short.configure(highlightcolor="black")
        self.Short.configure(justify='left')
        self.Short.configure(selectcolor="#d9d9d9")
        self.Short.configure(text='''SHORT''')
        self.Short.configure(variable=self.selectedButton,value="SHORT")


        self.Checkbutton1 = tk.Checkbutton(self.top)
        self.Checkbutton1.place(relx=0.635, rely=0.746, relheight=0.032
                , relwidth=0.280)
        self.Checkbutton1.configure(activebackground="beige")
        self.Checkbutton1.configure(activeforeground="black")
        self.Checkbutton1.configure(anchor='w')
        self.Checkbutton1.configure(background="#5b8ce6")
        self.Checkbutton1.configure(compound='left')
        self.Checkbutton1.configure(disabledforeground="#a3a3a3")
        self.Checkbutton1.configure(foreground="#000000")
        self.Checkbutton1.configure(highlightbackground="#d9d9d9")
        self.Checkbutton1.configure(highlightcolor="black")
        self.Checkbutton1.configure(justify='left')
        self.Checkbutton1.configure(selectcolor="#d9d9d9")
        self.Checkbutton1.configure(text='''İz Süren Kar Al''')
        self.Checkbutton1.configure(variable=self.che46)

















def start_up():
    alsattool_support.main()

if __name__ == '__main__':
    alsattool_support.main()




