#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.5
#  in conjunction with Tcl version 8.6
#    Aug 16, 2022 02:01:12 AM +03  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import alsattool
import backend



def get_data():
    x = str(_w1.Coin.get()).upper()
    y = float(_w1.Fiyat.get())
    z = float(_w1.Miktar.get())
    t = _w1.selectedButton.get()
    i = _w1.che46.get()

    return x,y,z,t,i

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = alsattool.Toplevel1(_top1)
    root.mainloop()


#
def coinismi(*args):

    sys.stdout.flush()

def fiyat(*args):

    sys.stdout.flush()

def kar_10(*args):
    temp = get_data()
    backend.izsüren_belirleme(temp[0], temp[1], temp[2], temp[3],10)
    sys.stdout.flush()

def kar_20(*args):
    temp = get_data()
    backend.izsüren_belirleme(temp[0], temp[1], temp[2], temp[3], 20)

    sys.stdout.flush()

def kar_30(*args):
    temp = get_data()
    backend.izsüren_belirleme(temp[0], temp[1], temp[2], temp[3], 30)

    sys.stdout.flush()

def kar_40(*args):
    temp = get_data()
    backend.izsüren_belirleme(temp[0], temp[1], temp[2], temp[3], 40)

    sys.stdout.flush()

def karsiz_cikis(*args):
    temp = get_data()
    backend.izsüren_belirleme(temp[0], temp[1], temp[2], temp[3], 5)

    sys.stdout.flush()

def miktar(*args):

    sys.stdout.flush()




def btn_limit_click(*args):
    temp = get_data()
    backend.pozisyon_belirleme(temp[0],temp[1],temp[2],temp[3],)


    sys.stdout.flush()

def btn_market_click(*args):


    sys.stdout.flush()

if __name__ == '__main__':
    alsattool.start_up()




